lib/pleroma/web/router.ex
    post("/statuses/:id/unreblog", StatusController, :unreblog)
    post("/statuses/:id/favourite", StatusController, :favourite)
    post("/statuses/:id/unfavourite", StatusController, :unfavourite)
    post("/statuses/:id/pin", StatusController, :pin)
    post("/statuses/:id/unpin", StatusController, :unpin)
    post("/statuses/:id/bookmark", StatusController, :bookmark)
    post("/statuses/:id/unbookmark", StatusController, :unbookmark)
    post("/statuses/:id/mute", StatusController, :mute_conversation)
    post("/statuses/:id/unmute", StatusController, :unmute_conversation)

    put("/scheduled_statuses/:id", ScheduledActivityController, :update)
    delete("/scheduled_statuses/:id", ScheduledActivityController, :delete)

    post("/polls/:id/votes", PollController, :vote)

    post("/media", MediaController, :create)
    put("/media/:id", MediaController, :update)

    delete("/lists/:id", ListController, :delete)
    post("/lists", ListController, :create)
    put("/lists/:id", ListController, :update)

    post("/lists/:id/accounts", ListController, :add_to_list)
    delete("/lists/:id/accounts", ListController, :remove_from_list)

    post("/filters", FilterController, :create)
    get("/filters/:id", FilterController, :show)
    put("/filters/:id", FilterController, :update)
    delete("/filters/:id", FilterController, :delete)

    post("/reports", ReportController, :create)

    post("/follows", AccountController, :follows)
    post("/accounts/:id/follow", AccountController, :follow)
    post("/accounts/:id/unfollow", AccountController, :unfollow)
    post("/accounts/:id/block", AccountController, :block)
    post("/accounts/:id/unblock", AccountController, :unblock)
    post("/accounts/:id/mute", AccountController, :mute)
    post("/accounts/:id/unmute", AccountController, :unmute)

    post("/follow_requests/:id/authorize", FollowRequestController, :authorize)
    post("/follow_requests/:id/reject", FollowRequestController, :reject)

    post("/domain_blocks", DomainBlockController, :create)
    delete("/domain_blocks", DomainBlockController, :delete)

    post("/push/subscription", SubscriptionController, :create)
    get("/push/subscription", SubscriptionController, :get)
    put("/push/subscription", SubscriptionController, :update)
    delete("/push/subscription", SubscriptionController, :delete)

    get("/markers", MarkerController, :index)
    post("/markers", MarkerController, :upsert)
  end

  scope "/api/web", Pleroma.Web do
    pipe_through(:authenticated_api)

    put("/settings", MastoFEController, :put_settings)
  end

  scope "/api/v1", Pleroma.Web.MastodonAPI do
    pipe_through(:api)

    post("/accounts", AccountController, :create)
    get("/accounts/search", SearchController, :account_search)

    get("/instance", InstanceController, :show)
    get("/instance/peers", InstanceController, :peers)

    post("/apps", AppController, :create)
    get("/apps/verify_credentials", AppController, :verify_credentials)

    get("/statuses/:id/card", StatusController, :card)
    get("/statuses/:id/favourited_by", StatusController, :favourited_by)
    get("/statuses/:id/reblogged_by", StatusController, :reblogged_by)

    get("/custom_emojis", CustomEmojiController, :index)

    get("/trends", MastodonAPIController, :empty_array)

    get("/timelines/public", TimelineController, :public)
    get("/timelines/tag/:tag", TimelineController, :hashtag)
    get("/timelines/list/:list_id", TimelineController, :list)

    get("/statuses", StatusController, :index)
    get("/statuses/:id", StatusController, :show)
    get("/statuses/:id/context", StatusController, :context)

    get("/polls/:id", PollController, :show)

    get("/accounts/:id/statuses", AccountController, :statuses)
    get("/accounts/:id/followers", AccountController, :followers)
    get("/accounts/:id/following", AccountController, :following)
    get("/accounts/:id", AccountController, :show)

    get("/search", SearchController, :search)
  end

  scope "/api/v2", Pleroma.Web.MastodonAPI do
    pipe_through(:api)
    get("/search", SearchController, :search2)
  end

  scope "/api", Pleroma.Web do
    pipe_through(:config)

    get("/help/test", TwitterAPI.UtilController, :help_test)
    post("/help/test", TwitterAPI.UtilController, :help_test)
    get("/statusnet/config", TwitterAPI.UtilController, :config)
    get("/statusnet/version", TwitterAPI.UtilController, :version)
    get("/pleroma/frontend_configurations", TwitterAPI.UtilController, :frontend_configurations)
  end

  scope "/api", Pleroma.Web do
    pipe_through(:api)

    get(
      "/account/confirm_email/:user_id/:token",
      TwitterAPI.Controller,
      :confirm_email,
      as: :confirm_email
    )
  end

  scope "/api", Pleroma.Web, as: :authenticated_twitter_api do
    pipe_through(:authenticated_api)

    get("/oauth_tokens", TwitterAPI.Controller, :oauth_tokens)
    delete("/oauth_tokens/:id", TwitterAPI.Controller, :revoke_token)

    post("/qvitter/statuses/notifications/read", TwitterAPI.Controller, :notifications_read)
  end

  pipeline :ap_service_actor do
    plug(:accepts, ["activity+json", "json"])
  end

  pipeline :ostatus do
    plug(:accepts, ["html", "xml", "atom", "activity+json", "json"])
    plug(Pleroma.Plugs.StaticFEPlug)
  end

  pipeline :oembed do
    plug(:accepts, ["json", "xml"])
  end

  scope "/", Pleroma.Web do
    pipe_through(:ostatus)
    pipe_through(:http_signature)

    get("/objects/:uuid", OStatus.OStatusController, :object)
    get("/activities/:uuid", OStatus.OStatusController, :activity)
    get("/notice/:id", OStatus.OStatusController, :notice)
    get("/notice/:id/embed_player", OStatus.OStatusController, :notice_player)

    get("/users/:nickname/feed", Feed.UserController, :feed, as: :user_feed)
    get("/users/:nickname", Feed.UserController, :feed_redirect, as: :user_feed)

    get("/tags/:tag", Feed.TagController, :feed, as: :tag_feed)
  end

  scope "/", Pleroma.Web do
    pipe_through(:browser)
    get("/mailer/unsubscribe/:token", Mailer.SubscriptionController, :unsubscribe)
  end

  pipeline :activitypub do
    plug(:accepts, ["activity+json", "json"])
    plug(Pleroma.Web.Plugs.HTTPSignaturePlug)
    plug(Pleroma.Web.Plugs.MappedSignatureToIdentityPlug)
  end

  scope "/", Pleroma.Web.ActivityPub do
    # XXX: not really ostatus
    pipe_through(:ostatus)

    get("/users/:nickname/outbox", ActivityPubController, :outbox)
  end

  pipeline :activitypub_client do
    plug(:accepts, ["activity+json", "json"])
    plug(:fetch_session)
    plug(Pleroma.Plugs.OAuthPlug)
    plug(Pleroma.Plugs.BasicAuthDecoderPlug)
    plug(Pleroma.Plugs.UserFetcherPlug)
    plug(Pleroma.Plugs.SessionAuthenticationPlug)
    plug(Pleroma.Plugs.LegacyAuthenticationPlug)
    plug(Pleroma.Plugs.AuthenticationPlug)
    plug(Pleroma.Plugs.UserEnabledPlug)
    plug(Pleroma.Plugs.SetUserSessionIdPlug)
    plug(Pleroma.Plugs.EnsureUserKeyPlug)
  end

  scope "/", Pleroma.Web.ActivityPub do
    pipe_through([:activitypub_client])

    get("/api/ap/whoami", ActivityPubController, :whoami)
    get("/users/:nickname/inbox", ActivityPubController, :read_inbox)

    post("/users/:nickname/outbox", ActivityPubController, :update_outbox)
    post("/api/ap/upload_media", ActivityPubController, :upload_media)

    get("/users/:nickname/followers", ActivityPubController, :followers)
    get("/users/:nickname/following", ActivityPubController, :following)
  end

  scope "/", Pleroma.Web.ActivityPub do
    pipe_through(:activitypub)
    post("/inbox", ActivityPubController, :inbox)
    post("/users/:nickname/inbox", ActivityPubController, :inbox)
  end

  scope "/relay", Pleroma.Web.ActivityPub do
    pipe_through(:ap_service_actor)

    get("/", ActivityPubController, :relay)

    scope [] do
      pipe_through(:http_signature)
      post("/inbox", ActivityPubController, :inbox)
    end

    get("/following", ActivityPubController, :following, assigns: %{relay: true})
    get("/followers", ActivityPubController, :followers, assigns: %{relay: true})
  end

  scope "/internal/fetch", Pleroma.Web.ActivityPub do
    pipe_through(:ap_service_actor)

    get("/", ActivityPubController, :internal_fetch)
    post("/inbox", ActivityPubController, :inbox)
  end

  scope "/.well-known", Pleroma.Web do
    pipe_through(:well_known)

    get("/host-meta", WebFinger.WebFingerController, :host_meta)
    get("/webfinger", WebFinger.WebFingerController, :webfinger)
    get("/nodeinfo", Nodeinfo.NodeinfoController, :schemas)
  end

  scope "/nodeinfo", Pleroma.Web do
    get("/:version", Nodeinfo.NodeinfoController, :nodeinfo)
  end

  scope "/", Pleroma.Web do
    pipe_through(:api)

    get("/web/manifest.json", MastoFEController, :manifest)
  end

  scope "/", Pleroma.Web do
    pipe_through(:mastodon_html)

    get("/web/login", MastodonAPI.AuthController, :login)
    delete("/auth/sign_out", MastodonAPI.AuthController, :logout)

    post("/auth/password", MastodonAPI.AuthController, :password_reset)

    get("/web/*path", MastoFEController, :index)
  end

  pipeline :remote_media do
  end

  scope "/proxy/", Pleroma.Web.MediaProxy do
    pipe_through(:remote_media)

    get("/:sig/:url", MediaProxyController, :remote)
    get("/:sig/:url/:filename", MediaProxyController, :remote)
  end

  if Pleroma.Config.get(:env) == :dev do
    scope "/dev" do
      pipe_through([:mailbox_preview])

      forward("/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox")
    end
  end

  scope "/", Pleroma.Web.MongooseIM do
    get("/user_exists", MongooseIMController, :user_exists)
    get("/check_password", MongooseIMController, :check_password)
  end

  scope "/", Fallback do
    get("/registration/:token", RedirectController, :registration_page)
    get("/:maybe_nickname_or_id", RedirectController, :redirector_with_meta)
    get("/api*path", RedirectController, :api_not_implemented)
    get("/*path", RedirectController, :redirector)

lib/pleroma/web/feed/feed_view.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2020 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.FeedView do
  use Phoenix.HTML
  use Pleroma.Web, :view

  alias Pleroma.Formatter
  alias Pleroma.Object
  alias Pleroma.User
  alias Pleroma.Web.MediaProxy

  require Pleroma.Constants

  @spec pub_date(String.t() | DateTime.t()) :: String.t()
  def pub_date(date) when is_binary(date) do
    date
    |> Timex.parse!("{ISO:Extended}")
    |> pub_date
  end

  def pub_date(%DateTime{} = date), do: Timex.format!(date, "{RFC822}")

  def prepare_activity(activity, opts \\ []) do
    object = activity_object(activity)

    actor =
      if opts[:actor] do
        Pleroma.User.get_cached_by_ap_id(activity.actor)
      end

    %{
      activity: activity,
      data: Map.get(object, :data),
      object: object,
      actor: actor
    }
  end

  def most_recent_update(activities) do
    with %{updated_at: updated_at} <- List.first(activities) do
      NaiveDateTime.to_iso8601(updated_at)
    end
  end

  def most_recent_update(activities, user) do
    (List.first(activities) || user).updated_at
    |> NaiveDateTime.to_iso8601()
  end

  def feed_logo do
    case Pleroma.Config.get([:feed, :logo]) do
      nil ->
        "#{Pleroma.Web.base_url()}/static/logo.png"

      logo ->
        "#{Pleroma.Web.base_url()}#{logo}"
    end
    |> MediaProxy.url()
  end

  def logo(user) do
    user
    |> User.avatar_url()
    |> MediaProxy.url()
  end

  def last_activity(activities), do: List.last(activities)

  def activity_object(activity), do: Object.normalize(activity)

  def activity_title(%{data: %{"content" => content}}, opts \\ %{}) do
    content
    |> Pleroma.Web.Metadata.Utils.scrub_html()
    |> Pleroma.Emoji.Formatter.demojify()
    |> Formatter.truncate(opts[:max_length], opts[:omission])
    |> escape()
  end

  def activity_content(%{data: %{"content" => content}}) do
    content
    |> String.replace(~r/[\n\r]/, "")
    |> escape()
  end

  def activity_content(_), do: ""

  def activity_context(activity), do: activity.data["context"]

  def attachment_href(attachment) do
    attachment["url"]
    |> hd()
    |> Map.get("href")
  end

  def attachment_type(attachment) do
    attachment["url"]
    |> hd()
    |> Map.get("mediaType")
  end

  def get_href(id) do
    with %Object{data: %{"external_url" => external_url}} <- Object.get_cached_by_ap_id(id) do
      external_url
    else
      _e -> id
    end
  end

  def escape(html) do
    html
    |> html_escape()
    |> safe_to_string()
  end
end

lib/pleroma/web/feed/tag_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2020 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.TagController do
  use Pleroma.Web, :controller

  alias Pleroma.Config
  alias Pleroma.Web.ActivityPub.ActivityPub
  alias Pleroma.Web.Feed.FeedView

  import Pleroma.Web.ControllerHelper, only: [put_in_if_exist: 3]

  def feed(conn, %{"tag" => raw_tag} = params) do
    {format, tag} = parse_tag(raw_tag)

    activities =
      %{"type" => ["Create"], "tag" => tag}
      |> put_in_if_exist("max_id", params["max_id"])
      |> ActivityPub.fetch_public_activities()

    conn
    |> put_resp_content_type("application/atom+xml")
    |> put_view(FeedView)
    |> render("tag.#{format}",
      activities: activities,
      tag: tag,
      feed_config: Config.get([:feed])
    )
  end

  @spec parse_tag(binary() | any()) :: {format :: String.t(), tag :: String.t()}
  defp parse_tag(raw_tag) when is_binary(raw_tag) do
    case Enum.reverse(String.split(raw_tag, ".")) do
      [format | tag] when format in ["atom", "rss"] -> {format, Enum.join(tag, ".")}
      _ -> {"rss", raw_tag}
    end
  end

  defp parse_tag(raw_tag), do: {"rss", raw_tag}
end

lib/pleroma/web/feed/user_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2020 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.UserController do
  use Pleroma.Web, :controller

  alias Fallback.RedirectController
  alias Pleroma.User
  alias Pleroma.Web.ActivityPub.ActivityPub
  alias Pleroma.Web.ActivityPub.ActivityPubController
  alias Pleroma.Web.Feed.FeedView

  import Pleroma.Web.ControllerHelper, only: [put_in_if_exist: 3]

  plug(Pleroma.Plugs.SetFormatPlug when action in [:feed_redirect])

  action_fallback(:errors)

  def feed_redirect(%{assigns: %{format: "html"}} = conn, %{"nickname" => nickname}) do
    with {_, %User{} = user} <- {:fetch_user, User.get_cached_by_nickname_or_id(nickname)} do
      RedirectController.redirector_with_meta(conn, %{user: user})
    end
  end

  def feed_redirect(%{assigns: %{format: format}} = conn, _params)
      when format in ["json", "activity+json"] do
    ActivityPubController.call(conn, :user)
  end

  def feed_redirect(conn, %{"nickname" => nickname}) do
    with {_, %User{} = user} <- {:fetch_user, User.get_cached_by_nickname(nickname)} do
      redirect(conn, external: "#{user_feed_url(conn, :feed, user.nickname)}.atom")
    end
  end

  def feed(conn, %{"nickname" => nickname} = params) do
    with {_, %User{} = user} <- {:fetch_user, User.get_cached_by_nickname(nickname)} do
      activities =
        %{
          "type" => ["Create"],
          "actor_id" => user.ap_id
        }
        |> put_in_if_exist("max_id", params["max_id"])
        |> ActivityPub.fetch_public_activities()

      conn
      |> put_resp_content_type("application/atom+xml")
      |> put_view(FeedView)
      |> render("user.xml",
        user: user,
        activities: activities,
        feed_config: Pleroma.Config.get([:feed])
      )
    end
  end

  def errors(conn, {:error, :not_found}) do
    render_error(conn, :not_found, "Not found")
  end

  def errors(conn, {:fetch_user, nil}), do: errors(conn, {:error, :not_found})

  def errors(conn, _) do
    render_error(conn, :internal_server_error, "Something went wrong")
  end
end

lib/pleroma/web/templates/feed/feed/_activity.xml.eex
<entry>
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <id><%= @data["id"] %></id>
  <title><%= activity_title(@object, Keyword.get(@feed_config, :post_title, %{})) %></title>
  <content type="html"><%= activity_content(@object) %></content>
  <published><%= @data["published"] %></published>
  <updated><%= @data["published"] %></updated>
  <ostatus:conversation ref="<%= activity_context(@activity) %>">
    <%= activity_context(@activity) %>
  </ostatus:conversation>
  <link href="<%= activity_context(@activity) %>" rel="ostatus:conversation"/>

  <%= if @data["summary"] do %>
    <summary><%= @data["summary"] %></summary>
  <% end %>

  <%= if @activity.local do %>
    <link type="application/atom+xml" href='<%= @data["id"] %>' rel="self"/>
    <link type="text/html" href='<%= @data["id"] %>' rel="alternate"/>
  <% else %>
    <link type="text/html" href='<%= @data["external_url"] %>' rel="alternate"/>
  <% end %>

  <%= for tag <- @data["tag"] || [] do %>
    <category term="<%= tag %>"></category>
  <% end %>

  <%= for attachment <- @data["attachment"] || [] do %>
    <link rel="enclosure" href="<%= attachment_href(attachment) %>" type="<%= attachment_type(attachment) %>"/>
  <% end %>

  <%= if @data["inReplyTo"] do %>
    <thr:in-reply-to ref='<%= @data["inReplyTo"] %>' href='<%= get_href(@data["inReplyTo"]) %>'/>
  <% end %>

  <%= for id <- @activity.recipients do %>
    <%= if id == Pleroma.Constants.as_public() do %>
      <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection" href="http://activityschema.org/collection/public"/>
    <% else %>
      <%= unless Regex.match?(~r/^#{Pleroma.Web.base_url()}.+followers$/, id) do %>
        <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="<%= id %>"/>
      <% end %>
    <% end %>
  <% end %>

  <%= for {emoji, file} <- @data["emoji"] || %{} do %>
    <link name="<%= emoji %>" rel="emoji" href="<%= file %>"/>
  <% end %>
</entry>

lib/pleroma/web/templates/feed/feed/_author.xml.eex
<author>
  <id><%= @user.ap_id %></id>
  <activity:object>http://activitystrea.ms/schema/1.0/person</activity:object>
  <uri><%= @user.ap_id %></uri>
  <poco:preferredUsername><%= @user.nickname %></poco:preferredUsername>
  <poco:displayName><%= @user.name %></poco:displayName>
  <poco:note><%= escape(@user.bio) %></poco:note>
  <summary><%= escape(@user.bio) %></summary>
  <name><%= @user.nickname %></name>
  <link rel="avatar" href="<%= User.avatar_url(@user) %>"/>
  <%= if User.banner_url(@user) do %>
    <link rel="header" href="<%= User.banner_url(@user) %>"/>
  <% end %>
  <%= if @user.local do %>
    <ap_enabled>true</ap_enabled>
  <% end %>
</author>

lib/pleroma/web/templates/feed/feed/_tag_activity.atom.eex
<entry>
    <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
    <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
    
    <%= render @view_module, "_tag_author.atom", assigns %>
    
    <id><%= @data["id"] %></id>
    <title><%= activity_title(@object, Keyword.get(@feed_config, :post_title, %{})) %></title>
    <content type="html"><%= activity_content(@object) %></content>

  <%= if @activity.local do %>
    <link type="application/atom+xml" href='<%= @data["id"] %>' rel="self"/>
    <link type="text/html" href='<%= @data["id"] %>' rel="alternate"/>
  <% else %>
    <link type="text/html" href='<%= @data["external_url"] %>' rel="alternate"/>
  <% end %>

    <published><%= @data["published"] %></published>
    <updated><%= @data["published"] %></updated>

    <ostatus:conversation ref="<%= activity_context(@activity) %>">
      <%= activity_context(@activity) %>
    </ostatus:conversation>
    <link href="<%= activity_context(@activity) %>" rel="ostatus:conversation"/>

   <%= if @data["summary"] do %>
    <summary><%= @data["summary"] %></summary>
   <% end %>
  
    <%= for id <- @activity.recipients do %>
      <%= if id == Pleroma.Constants.as_public() do %>
        <link rel="mentioned"
          ostatus:object-type="http://activitystrea.ms/schema/1.0/collection"
          href="http://activityschema.org/collection/public"/>
      <% else %>
        <%= unless Regex.match?(~r/^#{Pleroma.Web.base_url()}.+followers$/, id) do %>
          <link rel="mentioned"
            ostatus:object-type="http://activitystrea.ms/schema/1.0/person"
            href="<%= id %>" />
        <% end %>
      <% end %>
    <% end %>
  
    <%= for tag <- @data["tag"] || [] do %>
      <category term="<%= tag %>"></category>
    <% end %>

    <%= for {emoji, file} <- @data["emoji"] || %{} do %>
      <link name="<%= emoji %>" rel="emoji" href="<%= file %>"/>
    <% end %>
</entry>

lib/pleroma/web/templates/feed/feed/_tag_activity.xml.eex
<item>
  <title><%= activity_title(@object, Keyword.get(@feed_config, :post_title, %{})) %></title>
  
  
  <guid isPermalink="true"><%= activity_context(@activity) %></guid>
  <link><%= activity_context(@activity) %></link>
  <pubDate><%= pub_date(@data["published"]) %></pubDate>
  
  <description><%= activity_content(@object) %></description>
  <%= for attachment <- @data["attachment"] || [] do %>
    <enclosure url="<%= attachment_href(attachment) %>" type="<%= attachment_type(attachment) %>"/>
  <% end %>
  
</item>

lib/pleroma/web/templates/feed/feed/_tag_author.atom.eex
<author>
    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
    <id><%= @actor.ap_id %></id>
    <uri><%= @actor.ap_id %></uri>
    <name><%= @actor.nickname %></name>
    <summary><%= escape(@actor.bio) %></summary>
    <link rel="avatar" href="<%= User.avatar_url(@actor) %>"/>
    <%= if User.banner_url(@actor) do %>
      <link rel="header" href="<%= User.banner_url(@actor) %>"/>
    <% end %>
    <%= if @actor.local do %>
      <ap_enabled>true</ap_enabled>
    <% end %>
  
    <poco:preferredUsername><%= @actor.nickname %></poco:preferredUsername>        
    <poco:displayName><%= @actor.name %></poco:displayName>
    <poco:note><%= escape(@actor.bio) %></poco:note>    
</author>

lib/pleroma/web/templates/feed/feed/tag.atom.eex
<?xml version="1.0" encoding="UTF-8"?>

<feed xml:lang="en-US" xmlns="http://www.w3.org/2005/Atom"
      xmlns:thr="http://purl.org/syndication/thread/1.0"
      xmlns:georss="http://www.georss.org/georss"
      xmlns:activity="http://activitystrea.ms/spec/1.0/"
      xmlns:media="http://purl.org/syndication/atommedia"
      xmlns:poco="http://portablecontacts.net/spec/1.0"
      xmlns:ostatus="http://ostatus.org/schema/1.0"
      xmlns:statusnet="http://status.net/schema/api/1/">

    <id><%= '#{tag_feed_url(@conn, :feed, @tag)}.rss' %></id>
    <title>#<%= @tag %></title>

    <subtitle>These are public toots tagged with #<%= @tag %>. You can interact with them if you have an account anywhere in the fediverse.</subtitle>
    <logo><%= feed_logo() %></logo>
    <updated><%= most_recent_update(@activities) %></updated>
    <link rel="self" href="<%= '#{tag_feed_url(@conn, :feed, @tag)}.atom'  %>" type="application/atom+xml"/>
    <%= for activity <- @activities do %>
    <%= render @view_module, "_tag_activity.atom", Map.merge(assigns, prepare_activity(activity, actor: true)) %>
    <% end %>
</feed>

lib/pleroma/web/templates/feed/feed/tag.rss.eex
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:webfeeds="http://webfeeds.org/rss/1.0">
  <channel>


    <title>#<%= @tag %></title>
    <description>These are public toots tagged with #<%= @tag %>. You can interact with them if you have an account anywhere in the fediverse.</description>
    <link><%= '#{tag_feed_url(@conn, :feed, @tag)}.rss' %></link>
    <webfeeds:logo><%= feed_logo() %></webfeeds:logo>
    <webfeeds:accentColor>2b90d9</webfeeds:accentColor>
    <%= for activity <- @activities do %>
    <%= render @view_module, "_tag_activity.xml", Map.merge(assigns, prepare_activity(activity)) %>
    <% end %>
  </channel>
</rss>

lib/pleroma/web/templates/feed/feed/user.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<feed
  xmlns="http://www.w3.org/2005/Atom"
  xmlns:thr="http://purl.org/syndication/thread/1.0"
  xmlns:activity="http://activitystrea.ms/spec/1.0/"
  xmlns:poco="http://portablecontacts.net/spec/1.0"
  xmlns:ostatus="http://ostatus.org/schema/1.0">

  <id><%= user_feed_url(@conn, :feed, @user.nickname) <> ".atom" %></id>
  <title><%= @user.nickname <> "'s timeline" %></title>
  <updated><%= most_recent_update(@activities, @user) %></updated>
  <logo><%= logo(@user) %></logo>
  <link rel="self" href="<%= '#{user_feed_url(@conn, :feed, @user.nickname)}.atom' %>" type="application/atom+xml"/>

  <%= render @view_module, "_author.xml", assigns %>

  <%= if last_activity(@activities) do %>
    <link rel="next" href="<%= '#{user_feed_url(@conn, :feed, @user.nickname)}.atom?max_id=#{last_activity(@activities).id}' %>" type="application/atom+xml"/>
  <% end %>

  <%= for activity <- @activities do %>
  <%= render @view_module, "_activity.xml", Map.merge(assigns, prepare_activity(activity)) %>
  <% end %>
</feed>